import {
  validateThemeDefinition,
  type ThemeDefinition,
} from '@misoto22/kioku-ui';

/**
 * A complete implementation of the token contract. Rename it, change the
 * values, and register it with your ThemeProvider. Every role must be filled:
 * `validateThemeDefinition` rejects a partial theme at runtime rather than
 * letting an unfilled role fall back to something arbitrary.
 */
export const starterTheme: ThemeDefinition = validateThemeDefinition({
  id: 'starter',
  label: 'Starter',
  tokens: {
    'color-canvas': 'light-dark(#f6f5f2, #16151a)',
    'color-surface': 'light-dark(#ffffff, #1e1d23)',
    'color-surface-raised': 'light-dark(#ffffff, #26252c)',
    'color-surface-muted': 'light-dark(#eeece7, #2c2b33)',
    'color-text': 'light-dark(#1b1a1f, #f2f0ec)',
    'color-text-secondary': 'light-dark(#55525c, #c6c2cd)',
    'color-text-muted': 'light-dark(#7a7683, #98939f)',
    'color-text-on-accent': 'light-dark(#ffffff, #16151a)',
    'color-accent': 'light-dark(#3f5d8f, #9db6df)',
    'color-accent-hover': 'light-dark(#35507c, #b0c5e6)',
    'color-accent-active': 'light-dark(#2c4368, #c2d3ed)',
    'color-overlay-hover': 'light-dark(#0000000d, #ffffff14)',
    'color-overlay-active': 'light-dark(#0000001a, #ffffff24)',
    'color-disabled-surface': 'light-dark(#eceae6, #26252c)',
    'color-disabled-text': 'light-dark(#a5a1ac, #6d6975)',
    'color-focus': 'light-dark(#3f5d8f, #9db6df)',
    'border-default': 'light-dark(#dcd9d3, #35333c)',
    'border-strong': 'light-dark(#bdb9b2, #4a4752)',
    'border-interactive': 'light-dark(#3f5d8f, #9db6df)',
    'border-disabled': 'light-dark(#e4e2de, #2f2e36)',
    'border-width': '1px',
    'border-style': 'solid',
    'status-info-surface': 'light-dark(#e6edf8, #1f2a3d)',
    'status-info-text': 'light-dark(#274a7d, #a8c2e8)',
    'status-success-surface': 'light-dark(#e4f0e6, #1c2f22)',
    'status-success-text': 'light-dark(#2c5c39, #a5d3b1)',
    'status-warning-surface': 'light-dark(#f8efdc, #382e18)',
    'status-warning-text': 'light-dark(#7a5514, #e2c184)',
    'status-danger-surface': 'light-dark(#f9e6e5, #3a1f1f)',
    'status-danger-text': 'light-dark(#8c2f2b, #eba9a5)',
    'focus-width': '2px',
    'focus-offset': '2px',
    'typography-font-family-body': 'system-ui, sans-serif',
    'typography-font-family-heading': 'system-ui, sans-serif',
    'typography-font-family-display': 'system-ui, sans-serif',
    'typography-font-family-mono': 'ui-monospace, monospace',
    'typography-font-feature-settings': 'normal',
    'typography-font-size-xs': '0.75rem',
    'typography-font-size-sm': '0.875rem',
    'typography-font-size-md': '1rem',
    'typography-font-size-lg': '1.125rem',
    'typography-font-size-xl': '1.5rem',
    'typography-font-size2xl': '2rem',
    'typography-font-weight-regular': '400',
    'typography-font-weight-medium': '500',
    'typography-font-weight-strong': '650',
    'typography-line-height-body': '1.55',
    'typography-line-height-heading': '1.25',
    'typography-letter-spacing-title': '0.01em',
    'typography-letter-spacing-heading': '0.02em',
    'typography-letter-spacing-body': '0',
    'typography-letter-spacing-label': '0.04em',
    'typography-letter-spacing-eyebrow': '0.1em',
    'typography-letter-spacing-mono': '-0.01em',
    'spacing-xs': '0.25rem',
    'spacing-sm': '0.5rem',
    'spacing-md': '0.75rem',
    'spacing-lg': '1.25rem',
    'spacing-xl': '2rem',
    'spacing-2xl': '3rem',
    'radius-inner': '0.125rem',
    'radius-element': '0.375rem',
    'radius-container': '0.75rem',
    'radius-page': '1.25rem',
    'radius-full': '9999px',
    'size-control-sm': '1.75rem',
    'size-control-md': '2.25rem',
    'size-control-lg': '2.75rem',
    'size-hit-target': '2.75rem',
    'elevation-low': '0 1px 2px light-dark(#00000014, #00000066)',
    'elevation-medium': '0 4px 12px light-dark(#0000001f, #00000080)',
    'elevation-high': '0 12px 32px light-dark(#00000029, #00000099)',
    'texture-grain': 'none',
    'motion-duration-fast': '120ms',
    'motion-duration-moderate': '200ms',
    'motion-duration-slow': '900ms',
    'motion-easing-standard': 'cubic-bezier(0.2, 0, 0, 1)',
    'motion-easing-emphasized': 'cubic-bezier(0.3, 0, 0, 1)',
  },
});
