import {describe, expect, it} from 'vitest';

import {componentDocs, validateComponentDoc} from './index.js';

describe('componentDocs', () => {
  it('catalogs every stable component with complete, explicit inherited attributes', () => {
    expect(componentDocs.map(({name}) => name)).toEqual([
      'Text',
      'Heading',
      'Code',
      'Kbd',
      'Eyebrow',
      'Numeral',
      'Icon',
      'Stack',
      'Grid',
      'Section',
      'Card',
      'CardHeader',
      'CardFooter',
      'Divider',
      'Center',
      'List',
      'ListItem',
      'Item',
      'VisuallyHidden',
      'Button',
      'IconButton',
      'Badge',
      'StatusDot',
      'Field',
      'TextInput',
      'TextArea',
      'Toggle',
      'SegmentedControl',
      'CheckboxInput',
      'CheckboxList',
      'RadioList',
      'Switch',
      'Selector',
      'ComplexSelector',
      'Typeahead',
      'TypeaheadItem',
      'MultiSelector',
      'NumberInput',
      'FileInput',
      'Slider',
      'DateInput',
      'TimeInput',
      'DateTimeInput',
      'DateRangeInput',
      'Calendar',
      'FieldStatus',
      'InputGroup',
      'FormLayout',
      'EmptyState',
      'AsyncState',
      'Spinner',
      'Skeleton',
      'Alert',
      'Avatar',
      'AvatarGroup',
      'Thumbnail',
      'AspectRatio',
      'Box',
      'Banner',
      'Blockquote',
      'Citation',
      'CodeBlock',
      'Markdown',
      'MetadataList',
      'Timestamp',
      'Token',
      'Tokenizer',
      'ProgressBar',
      'Indicator',
      'Carousel',
      'Lightbox',
      'Layer',
      'Overlay',
      'Popover',
      'Tooltip',
      'Dialog',
      'AlertDialog',
      'BottomSheet',
      'BottomSheetSwitcher',
      'HoverCard',
      'DropdownMenu',
      'DropdownMenuItem',
      'ContextMenu',
      'MoreMenu',
      'Toast',
      'ToastProvider',
      'Table',
      'TableCaption',
      'TableHead',
      'TableBody',
      'TableRow',
      'TableHeaderCell',
      'TableCell',
      'MetricGrid',
      'HStack',
      'VStack',
      'ButtonGroup',
      'ToggleButton',
      'ToggleButtonGroup',
      'ClickableCard',
      'SelectableCard',
      'Collapsible',
      'Resizable',
      'ResizeHandle',
      'OverflowList',
      'TreeList',
      'CommandPalette',
      'PowerSearch',
      'ChatLayout',
      'ChatMessageList',
      'ChatMessage',
      'ChatMessageMetadata',
      'ChatSystemMessage',
      'ChatToolCalls',
      'ChatComposer',
      'TabList',
      'Breadcrumbs',
      'Pagination',
      'NavIcon',
      'NavItem',
      'NavMenu',
      'TopNav',
      'TopNavMenu',
      'TopNavMegaMenu',
      'TopNavMegaMenuFeaturedCard',
      'SideNav',
      'SideNavSection',
      'MobileNav',
      'Toolbar',
      'Outline',
      'Layout',
      'AppShell',
      'Link',
      'LinkProvider',
      'InternationalizationProvider',
      'ThemeProvider',
    ]);

    for (const doc of componentDocs) {
      expect(validateComponentDoc(doc)).toEqual([]);
      expect(doc.inheritedProps).toHaveLength(1);
    }

    const documentedProps = Object.fromEntries(
      componentDocs.map((doc) => [
        doc.name,
        doc.props.map((prop) => prop.name),
      ]),
    );
    expect(documentedProps).toMatchObject({
      Alert: ['icon', 'tone'],
      AlertDialog: [
        'children',
        'description',
        'footer',
        'onDismiss',
        'open',
        'size',
        'title',
      ],
      AspectRatio: ['children', 'ratio'],
      AsyncState: ['children', 'state'],
      AppShell: [
        'aside',
        'children',
        'contentPadding',
        'footer',
        'header',
        'pageHead',
        'pageIndex',
        'sidebar',
        'skipLinkLabel',
      ],
      Avatar: ['name', 'size', 'src'],
      AvatarGroup: ['label', 'max', 'members', 'size'],
      Badge: ['tone'],
      Banner: ['actions', 'children', 'tone'],
      Blockquote: ['attribution', 'children'],
      BottomSheet: ['children', 'onDismiss', 'open', 'title'],
      BottomSheetSwitcher: [
        'backLabel',
        'defaultViewId',
        'onDismiss',
        'onViewChange',
        'open',
        'viewId',
        'views',
      ],
      Breadcrumbs: ['items', 'label', 'separator'],
      Button: ['loading', 'size', 'variant'],
      ButtonGroup: ['children', 'label', 'orientation'],
      Calendar: [
        'defaultValue',
        'formatDay',
        'formatMonth',
        'label',
        'max',
        'min',
        'onValueChange',
        'value',
      ],
      Card: ['children', 'elevation'],
      Carousel: ['children', 'label', 'nextLabel', 'previousLabel'],
      ChatComposer: ['disabled', 'label', 'onSend', 'placeholder', 'sendLabel'],
      ChatLayout: ['composer'],
      ChatMessage: ['author', 'authorName', 'pending'],
      ChatMessageList: ['label'],
      ChatToolCalls: ['calls', 'label'],
      CheckboxList: [
        'defaultValue',
        'legend',
        'onValueChange',
        'options',
        'value',
      ],
      CheckboxInput: [
        'checked',
        'defaultChecked',
        'description',
        'indeterminate',
        'label',
        'onCheckedChange',
      ],
      Citation: ['children', 'href', 'marker'],
      ClickableCard: ['children'],
      Code: ['children'],
      CodeBlock: ['wrap', 'code', 'copiedLabel', 'copyLabel', 'language'],
      Collapsible: ['children', 'defaultOpen', 'label', 'onOpenChange', 'open'],
      CommandPalette: [
        'commands',
        'emptyMessage',
        'label',
        'onDismiss',
        'onRun',
        'open',
        'placeholder',
      ],
      ComplexSelector: [
        'defaultValue',
        'groups',
        'onValueChange',
        'placeholder',
        'value',
      ],
      ContextMenu: ['children', 'label', 'menu'],
      DateTimeInput: ['defaultValue', 'onValueChange', 'value'],
      DateRangeInput: [
        'defaultValue',
        'endLabel',
        'legend',
        'onValueChange',
        'startLabel',
        'value',
      ],
      DateInput: ['defaultValue', 'onValueChange', 'value'],
      Dialog: [
        'children',
        'description',
        'dismissOnOutsideClick',
        'footer',
        'onDismiss',
        'open',
        'size',
        'title',
      ],
      CardFooter: ['children'],
      CardHeader: ['children'],
      DropdownMenu: [
        'alignment',
        'anchorRef',
        'children',
        'label',
        'onDismiss',
        'open',
        'placement',
      ],
      DropdownMenuItem: ['description', 'leading', 'trailing'],
      EmptyState: ['action', 'detail', 'size', 'title', 'visual'],
      Eyebrow: ['children', 'tone'],
      Field: [
        'controlId',
        'description',
        'label',
        'necessity',
        'status',
        'statusTone',
      ],
      FileInput: ['onFilesChange'],
      FieldStatus: ['children', 'tone'],
      FormLayout: ['actions', 'children', 'columns'],
      HStack: ['align', 'gap', 'justify', 'wrap'],
      HoverCard: [
        'alignment',
        'children',
        'closeDelay',
        'content',
        'label',
        'openDelay',
        'placement',
      ],
      Icon: ['label', 'size', 'tone'],
      IconButton: ['aria-label', 'loading', 'size', 'variant'],
      InternationalizationProvider: [
        'children',
        'direction',
        'locale',
        'messages',
      ],
      Indicator: ['children', 'count', 'label', 'max', 'tone'],
      InputGroup: ['children', 'prefix', 'suffix'],
      Item: ['description', 'leading', 'trailing'],
      Kbd: ['children'],
      Layer: ['children', 'container'],
      Heading: ['family', 'level', 'size'],
      Lightbox: ['children', 'closeLabel', 'onDismiss', 'open', 'title'],
      Markdown: ['source'],
      MetadataList: ['entries', 'layout'],
      MetricGrid: ['items'],
      MobileNav: ['children', 'closeLabel', 'label', 'title'],
      MoreMenu: ['alignment', 'children', 'label', 'placement'],
      NumberInput: ['defaultValue', 'onValueChange', 'value'],
      Numeral: ['children'],
      Outline: ['currentHref', 'entries', 'label'],
      NavMenu: ['children', 'label', 'orientation'],
      NavItem: ['current', 'href', 'leading'],
      MultiSelector: [
        'emptyMessage',
        'label',
        'onValueChange',
        'options',
        'removeLabel',
        'value',
      ],
      NavIcon: ['children'],
      OverflowList: ['entries', 'overflowLabel', 'visibleCount'],
      Overlay: [
        'children',
        'dismissOnOutsideClick',
        'lockScroll',
        'onDismiss',
        'open',
        'scrim',
        'trapFocus',
      ],
      Pagination: ['label', 'onChange', 'page', 'pageCount', 'siblingCount'],
      Popover: [
        'alignment',
        'anchorRef',
        'children',
        'offset',
        'onDismiss',
        'open',
        'placement',
      ],
      Layout: [
        'aside',
        'children',
        'contentPadding',
        'footer',
        'header',
        'mainId',
        'pageHead',
        'pageIndex',
        'sidebar',
      ],
      Link: ['href'],
      LinkProvider: ['children', 'renderLink'],
      List: ['gap', 'variant'],
      ListItem: ['children'],
      PowerSearch: [
        'filters',
        'label',
        'onFiltersChange',
        'onSearch',
        'placeholder',
        'submitLabel',
      ],
      ProgressBar: ['label', 'max', 'value'],
      Resizable: [
        'children',
        'handleLabel',
        'max',
        'min',
        'onSizeChange',
        'panel',
        'size',
        'step',
      ],
      ResizeHandle: [
        'label',
        'max',
        'min',
        'onValueChange',
        'orientation',
        'step',
        'value',
      ],
      SegmentedControl: [
        'aria-label',
        'aria-labelledby',
        'defaultValue',
        'disabled',
        'onValueChange',
        'options',
        'orientation',
        'value',
      ],
      SelectableCard: ['description', 'label', 'multiple'],
      SideNavSection: ['children', 'title'],
      Selector: [
        'defaultValue',
        'onValueChange',
        'options',
        'placeholder',
        'value',
      ],
      RadioList: [
        'defaultValue',
        'legend',
        'onValueChange',
        'options',
        'value',
      ],
      SideNav: ['children', 'footer'],
      Skeleton: ['label'],
      Slider: [
        'defaultValue',
        'formatValue',
        'max',
        'min',
        'onValueChange',
        'step',
        'value',
      ],
      Spinner: ['label'],
      StatusDot: ['aria-label', 'tone'],
      Switch: ['defaultPressed', 'disabled', 'onPressedChange', 'pressed'],
      TabList: ['label', 'onSelect', 'selectedId', 'tabs'],
      Table: ['children', 'density', 'dividers'],
      TableBody: ['children'],
      TableCaption: ['children'],
      TableCell: ['children', 'numeric'],
      TableHead: ['children'],
      TableHeaderCell: ['children', 'scope', 'numeric'],
      TableRow: ['selected', 'children'],
      Thumbnail: ['alt', 'fallback', 'size', 'src'],
      Timestamp: ['format', 'value'],
      ToggleButton: ['defaultPressed', 'onPressedChange', 'pressed', 'size'],
      Token: ['children', 'leading', 'onRemove', 'removeLabel'],
      Tokenizer: [
        'label',
        'onValueChange',
        'placeholder',
        'removeLabel',
        'value',
      ],
      TopNav: ['actions', 'brand', 'children'],
      Toolbar: ['children', 'label', 'orientation'],
      Text: ['size', 'tone'],
      TreeList: [
        'expandedIds',
        'label',
        'nodes',
        'onExpandedChange',
        'onSelect',
        'selectedId',
      ],
      Typeahead: [
        'emptyMessage',
        'inputValue',
        'onInputValueChange',
        'onSelect',
        'options',
      ],
      TimeInput: ['defaultValue', 'onValueChange', 'value'],
      Toast: ['action', 'description', 'title', 'tone'],
      ToastProvider: ['children', 'label'],
      TextArea: [
        'aria-invalid',
        'defaultValue',
        'disabled',
        'onValueChange',
        'readOnly',
        'required',
        'value',
      ],
      TextInput: [
        'aria-invalid',
        'defaultValue',
        'disabled',
        'onValueChange',
        'readOnly',
        'required',
        'value',
      ],
      Toggle: ['defaultPressed', 'disabled', 'onPressedChange', 'pressed'],
      Tooltip: ['alignment', 'children', 'content', 'delay', 'placement'],
      ThemeProvider: [
        'children',
        'defaultDensity',
        'defaultThemeId',
        'persistence',
        'themes',
      ],
      VStack: ['align', 'gap'],
    });
  });

  it('documents ThemeProvider with host-supplied theme configuration', () => {
    expect(
      componentDocs.find(({name}) => name === 'ThemeProvider')?.example,
    ).toBe(
      '<ThemeProvider defaultThemeId={hostDefaultThemeId} themes={hostThemes}>...</ThemeProvider>',
    );
  });

  it('links ThemeProvider metadata to a product-neutral Storybook fixture', () => {
    expect(
      componentDocs.find(({name}) => name === 'ThemeProvider')?.storyId,
    ).toBe('core-theme-provider--default');
  });
});
